dictionary = {
    'f0' : 'hour',
    'f1' : 'is_holiday',
    'f2' : 'avtive_level',
    'f3' : 'gender',
    'f4' : 'age',
    'f5' : 'city_level',
    'f6' : 'user_read_time',
    'f7' : 'user_read_complete',
    'f8' : 'titlelength',
    'f9' : 'coverpicnum',
    'f10':  'quality_score',
    'f11':  'account_score',
    'f12':  'article_read_complete',
    'f13':  'article_read_time',
    'f14':  'comments',
    'f15':  'zan',
    'f16':  'share',
    'f17':  'channel_click_rate',
    'f18':  'channel_comment_rate',
    'f19':  'channel_like_rate',
    'f20':  'click_rate',
    'f21':  'male_click_rate',
    'f22':  'female_click_rate',
    'f23':  '1_11_click_rate',
    'f24':  '12_15_click_rate',
    'f25':  '16_18_click_rate',
    'f26':  '19_23_click_rate',
    'f27':  '24_30_click_rate',
    'f28':  '31_40_click_rate',
    'f29':  '41_50_click_rate',
    'f30':  'account_read_score',
    'f31':  'account_click_score',
    'f32':  'account_like_score',
    'f33':  'account_comment_score',
    'f34':  'account_health_score',
    'f35':  'account_res_score'
}