dictionary = {
   'f0':  'monday',
   'f1':  'tuesday',
   'f2':  'wednesday',
   'f3':  'thursday',
   'f4':  'friday',
   'f5':  'saturday',
   'f6':  'sunday',
   'f7':  'hour',
   'f8':  'is_holiday',
   'f9':  'avtive_level',
   'f10': 'gender',
   'f11': 'age',
   'f12': 'city_level',
   'f13': 'user_read_time',
   'f14': 'user_read_complete',
   'f15': 'titlelength',
   'f16': 'coverpicnum',
   'f17': 'quality_score',
   'f18': 'account_score',
   'f19': 'article_read_complete',
   'f20': 'article_read_time',
   'f21': 'comments',
   'f22': 'zan',
   'f23': 'share',
   'f24': 'channel_click_rate',
   'f25': 'channel_comment_rate',
   'f26': 'channel_like_rate',
   'f27': 'click_rate',
   'f28': 'male_click_rate',
   'f29': 'female_click_rate',
   'f30': '1_11_click_rate',
   'f31': '12_15_click_rate',
   'f32': '16_18_click_rate',
   'f33': '19_23_click_rate',
   'f34': '24_30_click_rate',
   'f35': '31_40_click_rate',
   'f36': '41_50_click_rate',
   'f37': 'account_read_score',
   'f38': 'account_click_score',
   'f39': 'account_like_score',
   'f40': 'account_comment_score',
   'f41': 'account_health_score',
   'f42': 'account_res_score',
   'f43' :   'other', 
   'f44' :   'ports', 
   'f45' :   'tech', 
   'f46' :   'ent', 
   'f47' :   'auto', 
   'f48' :   'women',
   'f49' :   'astro',
   'f50' :   'house',
   'f51' :   'digital',
   'f52' :   'finance',
   'f53' :   'game',
   'f54' :   'mil',
   'f55' :   'social',
   'f56' :   'cul',
   'f57' :   'politics',
   'f58' :   'baby',
   'f59' :   'edu',
   'f60' :   'food',
   'f61' :   'funny',
   'f62' :   'religion',
   'f63' :   'health',
   'f64' :   'travel',
   'f65' :   'world',
   'f66' :   'pet',
   'f67' :   'inspiration',
   'f68' :   'gif',
   'f69' :   'video',
   'f70' :   'weather',
   'f71' :   'history',
   'f72' :   'emotion',
   'f73' :   'picture',
   'f74' :   'beauty',
   'f75' :   'comic',
   'f76' :   'job',
   'f77' :   'abroad',
   'f78' :   'agriculture',
   'f79' :   'creativity',
   'f80' :   'houseliving',
   'f81' :   'law',
   'f82' :   'lifestyle',
   'f83' :   'lottery',
   'f84' :   'science',
   'f85' :   'photography',
   'f86' :   'career',
   'f87' :   'life',
   'f88' :   'wedding',
   'f89' :   'qipa',
   'f90' :   'hardcore',
   'f91' :   'ghost',
   'f92' :   'meitu',
   'f93' :   'basketball',
   'f94' :   'football',
   'f95' :   'athletics',
   'f96' :   'badmiton',
   'f97' :   'basketball',
   'f98' :   'chess',
   'f99' :   'pingpang',
   'f100' :   'swimming',
   'f101' :   'tennis',
   'f102' :   'volleyball',
   'f103' :   'sports_cba',
   'f104' :   'sports_nba',
   'f105' :   'sports_boji',
   'f106' :   'sports_dejia',
   'f107' :   'golf',
   'f108' :   'sports_outdoor',
   'f109' :   'sports_huwaiyundong',
   'f110' :   'fitness',
   'f111' :   'sports_paobu',
   'f112' :   'sports_saiche',
   'f113' :   'sports_taiqiu',
   'f114' :   'sports_xijia',
   'f115' :   'sports_yijia',
   'f116' :   'sports_yingchao',
   'f117' :   'sports_zhongchao',
   'f118' :   'football',
   'f119' :   'sports_ski',
   'f120' :   'sports_zhongguozuqiu', 
   'f121' :   'sports_gossip',
   'f122' :   'sports_baobei',
   'f123' :   'sports_bike',
   'f124' :   'huashi',
   'f125' :   'zhongguoxiangqi',
   'f126' :   'weiqi',
   'f127' :   'ouguan',
   'f128' :   'dezhoupuke',
   'f129' :   'qiaopai',
   'f130' :   'internet',
   'f131' :   'intelligent',
   'f132' :   'networksecurity',
   'f133' :   'phone',
   'f134' :   'software',
   'f135' :   'science',
   'f136' :   'tech_vr',
   'f137' :   'tech_artifical',
   'f138' :   'tech_communication',
   'f139' :   'tech_famous',
   'f140' :   'tech_iot',
   'f141' :   'tech_megadata',
   'f142' :   'tech_o2o',
   'f143' :   'tech_retail',
   'f144' :   'tech_sns',
   'f145' :   'tech_uav',
   'f146' :   'tech_venture',
   'f147' :   'tech_yun',
   'f148' :   'tech_investment',
   'f149' :   'tech_programmer',
   'f150' :   'tech_product',
   'f151' :   'tech_autopilot',
   'f152' :   'tech_3d',
   'f153' :   'film',
   'f154' :   'tvplay',
   'f155' :   'show',
   'f156' :   'drama',
   'f157' :   'music',
   'f158' :   'star',
   'f159' :   'ent_hanyu',
   'f160' :   'ent_hongkong',
   'f161' :   'ent_janpan',
   'f162' :   'ent_western',
   'f163' :   'ent_americantv',
   'f164' :   'ent_china',
   'f165' :   'ent_englishtv',
   'f166' :   'ent_quyi',
   'f167' :   'ent_talkshow',
   'f168' :   'ent_xiangsheng',
   'f169' :   'ent_xiaoping',
   'f170' :   'star_all',
   'f171' :   'auto_yongche',
   'f172' :   'auto_ceping',
   'f173' :   'auto_chanye',
   'f174' :   'auto_daogou',
   'f175' :   'auto_diandongche',
   'f176' :   'auto_xinche',
   'f177' :   'auto_takecare',
   'f178' :   'auto_suv',
   'f179' :   'auto_secondhand',
   'f180' :   'auto_refit',
   'f181' :   'auto_skills',
   'f182' :   'auto_weird',
   'f183' :   'auto_tags',
   'f184' :   'women_meiti',
   'f185' :   'women_zhubao',
   'f186' :   'women_shizhuang',
   'f187' :   'women_hair',
   'f188' :   'women_luxury',
   'f189' :   'women_wanbiao',
   'f190' :   'women_makeup',
   'f191' :   'women_skincare',
   'f192' :   'women_beauty',
   'f193' :   'women_man',
   'f194' :   'women_tattoo',
   'f195' :   'women_makeup_meimao',
   'f196' :   'women_makeup_yanz...', 
   'f197' :   'women_makeup_chun...', 
   'f198' :   'women_makeup_lian...', 
   'f199' :   'women_skincare_qi...', 
   'f200' :   'women_skincare_xiufu', 
   'f201' :   'women_skincare_bsbs',
   'f202' :   'women_skincare_fa...', 
   'f203' :   'women_meiti_meijia',
   'f204' :   'women_meiti_meifa',
   'f205' :   'women_meiti_xiang...', 
   'f206' :   'women_meiti_sssx',
   'f207' :   'women_shizhuang_dpmj', 
   'f208' :   'women_shizhuang_cljp', 
   'f209' :   'astro_shengxiao',
   'f210' :   'astro_mingli',
   'f211' :   'astro_psytest',
   'f212' :   'astro_xingzuo',
   'f213' :   'astro_fengshui',
   'f214' :   'house_chuweidianqi',
   'f215' :   'house_duorouzhiwu',
   'f216' :   'house_fengshui',
   'f217' :   'house_jiaju',
   'f218' :   'house_zhuangxiu',
   'f219' :   'house_lease',
   'f220' :   'house_oversea',
   'f221' :   'house_pm',
   'f222' :   'house_sell',
   'f223' :   'digital_phone',
   'f224' :   'digital_hardware',
   'f225' :   'digital_industry',
   'f226' :   'digital_iphone',
   'f227' :   'digital_chip',
   'f228' :   'digital_chuandais...', 
   'f229' :   'digital_jiadian',
   'f230' :   'digital_kuwan',
   'f231' :   'digital_pad',
   'f232' :   'digital_pc',
   'f233' :   'digital_tv',
   'f234' :   'bank',
   'f235' :   'bond',
   'f236' :   'frgexchange',
   'f237' :   'fund',
   'f238' :   'futures',
   'f239' :   'insurance',
   'f240' :   'interfinance',
   'f241' :   'inverstment',
   'f242' :   'macroeco',
   'f243' :   'mngmoney',
   'f244' :   'stock',
   'f245' :   'finance_bit',
   'f246' :   'finance_business',
   'f247' :   'finance_corporation',
   'f248' :   'finance_famous',
   'f249' :   'finance_internation',
   'f250' :   'finance_xintuo',
   'f251' :   'finance_energy',
   'f252' :   'finance_metal',
   'f253' :   'finance_hkstock',
   'f254' :   'finance_usstock',
   'f255' :   'stock_share',
   'f256' :   'stock_marco',
   'f257' :   'chemical_futures',
   'f258' :   'energy_futures',
   'f259' :   'agricultural_futures', 
   'f260' :   'stock_market',
   'f261' :   'metal_futures',
   'f262' :   'stock_index',
   'f263' :   'game_dianjing',
   'f264' :   'game_industry',
   'f265' :   'game_pandian',
   'f266' :   'game_shouyou',
   'f267' :   'game_wangyou',
   'f268' :   'game_youxiji',
   'f269' :   'game_esports',
   'f270' :   'game_baoxue',
   'f271' :   'game_cf',
   'f272' :   'game_dianjing_ent',
   'f273' :   'game_dianjing_info',
   'f274' :   'game_dnf',
   'f275' :   'game_lol_ent',
   'f276' :   'game_lol_gonglue',
   'f277' :   'game_lol_neirong',
   'f278' :   'game_lol_yingxiong',
   'f279' :   'game_wzry_ent',
   'f280' :   'game_wzry_gonglue',
   'f281' :   'game_wzry_neirong',
   'f282' :   'game_wzry_yxpandian',
   'f283' :   'game_yingyangshi',
   'f284' :   'game_zhubo',
   'f285' :   'game_tags',
   'f286' :   'game_wangzhe',
   'f287' :   'mil_zhongguojunqing',
   'f288' :   'mil_hangkonghangtian', 
   'f289' :   'mil_war',
   'f290' :   'mil_weapon',
   'f291' :   'mil_internation',
   'f292' :   'mil_changguidaodan',
   'f293' :   '    mil_hangmu',
   'f294' :   '  mil_hedaodan',
   'f295' :   ' mil_hongzhaji',
   'f296' :   '  mil_jianting',
   'f297' :   '  mil_qianting',
   'f298' :   '  mil_yunshuji',
   'f299' :   ' mil_zhandouji',
   'f300' :   'mil_zhishengji',
   'f301' :   ' social_qiwendieshi',
   'f302' :   'social_shipinanquan',
   'f303' :   'social_jihuashengyu',
   'f304' :   'social_huanjingbaohu', 
   'f305' :   'social_community',
   'f306' :   'social_mingsheng',
   'f307' :   'social_cishan',
   'f308' :   'social_offense',
   'f309' :   'social_traffic',
   'f310' :   'worldsociety',
   'f311' :   'traffic',
   'f312' :   'cul_dushu',
   'f313' :   'cul_wenwu',
   'f314' :   'cul_sheying',
   'f315' :   'cul_yishu',
   'f316' :   'cul_building',
   'f317' :   'cul_collect',
   'f318' :   'cul_painting',
   'f319' :   'cul_shufa',
   'f320' :   'cul_magic',
   'f321' :   'cul_instrument',
   'f322' :   'cul_wenxue',
   'f323' :   'cul_guoxue',
   'f324' :   'cul_minsu',
   'f325' :   'cul_shige',
   'f326' :   'cul_shougongyi',
   'f327' :   'cul_philosophy',
   'f328' :   'politics_internat...', 
   'f329' :   'politics_domestic',
   'f330' :   'baby_yunchan',
   'f331' :   'baby_qinzichengchang', 
   'f332' :   ' baby_autism',
   'f333' :   'baby_prepare',
   'f334' :   'baby_postnatal',
   'f335' :   ' baby_weird',
   'f336' :   ' edu_abroad',
   'f337' :   'edu_college',
   'f338' :   'edu_primary', 
   'f339' :   ' edu_skills',
   'f340' :   ' edu_gaokao',
   'f341' :   ' edu_kaoyan',
   'f342' :   'edu_gongwuyuan',
   'f343' :   'edu_english',
   'f344' :   ' edu_gmat',
   'f345' :   'edu_ielts',
   'f346' :   '  edu_sat',
   'f347' :   '  edu_gre',
   'f348' :   '  edu_mba',
   'f349' :   'edu_accountexam',
   'f350' :   'edu_lawexam',
   'f351' :   'edu_online',
   'f352' :   'edu_oversea',
   'f353' :   'edu_toelf',
   'f354' :   'edu_junior',
   'f355' :   'edu_weird',
   'f356' :   'food_zhongcan',
   'f357' :   'food_caipu',
   'f358' :   'food_ribenliaoli',
   'f359' :   'food_guide',
   'f360' :   'food_pengrenjiqiao',
   'f361' :   'food_xiaochi',
   'f362' :   'food_drink_alcoho...', 
   'f363' :   'food_fruit',
   'f364' :   'food_cuisine_zhej...', 
   'f365' :   'food_material',
   'f366' :   'food_dessert',
   'f367' :   'food_cuisine_fujian',
   'f368' :   'food_cuisine_shanxi',
   'f369' :   'food_restaurant',
   'f370' :   'food_foreign_asia',
   'f371' :   'food_cuisine',
   'f372' :   'food_drink_alcoho...', 
   'f373' :   'food_cuisine_beijing', 
   'f374' :   'food_cuisine_jiangsu', 
   'f375' :   'food_drink_alcoho...', 
   'f376' :   'food_foreign_italy',
   'f377' :   'food_cuisine_dongbei', 
   'f378' :   'food_story',
   'f379' :   'food_cuisine_qing...', 
   'f380' :   'food_drink_alcoho...', 
   'f381' :   'food_cuisine_henan',
   'f382' :   'food_cuisine_guan...', 
   'f383' :   'food_cuisine_hebei',
   'f384' :   'food_idea',
   'f385' :   'food_lingshi',
   'f386' :   'food_palace',
   'f387' :   'food_foreign_usa',
   'f388' :   'food_cuisine_xizhang', 
   'f389' :   'food_cuisine_shan...', 
   'f390' :   'food_foreign_mexico',
   'f391' :   'food_cuisine_hunan',
   'f392' :   'food_cuisine_shan...', 
   'f393' :   'food_cuisine_hubei',
   'f394' :   'food_cuisine_yungui',
   'f395' :   'food_foreign',
   'f396' :   'food_cuisine_hainan',
   'f397' :   'food_cuisine_anhui',
   'f398' :   'food_drink_alcohol',
   'f399' :   'food_cuisine_xibei',
   'f400' :   'food_drink_alcoho...', 
   'f401' :   'food_homely',
   'f402' :   'food_drink_alcoho...', 
   'f403' :   'food_cuisine_sicuan',
   'f404' :   'food_cuisine_jiangxi', 
   'f405' :   'food_coffee',
   'f406' :   'food_foreign_france',
   'f407' :   'food_cuisine_gangtai', 
   'f408' :   'food_foreign_korea',
   'f409' :   'funny_pic',
   'f410' :   'funny_story',
   'f411' :   'religion_buddhism',
   'f412' :   'religion_christian',
   'f413' :   'health_jianfei',
   'f414' :   'health_yangsheng',
   'f415' :   'health_zhongyi',
   'f416' :   'health_kouqianghuli',
   'f417' :   'health_fuke',
   'f418' :   'health_aizheng',
   'f419' :   'health_shipinganquan', 
   'f420' :   'health_chuanranbing',
   'f421' :   'health_pifubing',
   'f422' :   'health_psychology',
   'f423' :   'health_control',
   'f424' :   'health_old',
   'f425' :   'health_sex',
   'f426' :   'health_man',
   'f427' :   'health_woman',
   'f428' :   'health_care',
   'f429' :   'health_baby',
   'f430' :   'health_products',
   'f431' :   'health_food',
   'f432' :   'health_nutrition',
   'f433' :   'health_zyyangsheng',
   'f434' :   'travel_africa',
   'f435' :   'travel_america',
   'f436' :   'travel_demostic',
   'f437' :   'travel_europa',
   'f438' :   'travel_hm',
   'f439' :   'travel_information',
   'f440' :   'travel_jk',
   'f441' :   'travel_soucheastasia', 
   'f442' :   'travel_australia',
   'f443' :   'travel_car',
   'f444' :   'travel_line',
   'f445' :   'travel_korea',
   'f446' :   'travel_south_america', 
   'f447' :   'travel_tours',
   'f448' :   'travel_north_america', 
   'f449' :   'travel_southeast_...', 
   'f450' :   'travel_middle_east',
   'f451' :   'pet_weird',
   'f452' :   'history_kangrizha...', 
   'f453' :   'history_ancient',
   'f454' :   'history_mingqing',
   'f455' :   'history_minguo',
   'f456' :   'history_party',
   'f457' :   'history_wenge',
   'f458' :   'history_zhiqing',
   'f459' :   'history_gaigekaifang', 
   'f460' :   'history_world',
   'f461' :   'history_wwi',
   'f462' :   'history_wwii',
   'f463' :   'history_jianguochuqi', 
   'f464' :   'history_kangmeiyu...', 
   'f465' :   'history_yuanyue',
   'f466' :   'history_sanfanwufan',
   'f467' :   'history_foreign',
   'f468' :   'history_jinxian',
   'f469' :   'emotion_inlove',
   'f470' :   'emotion_marriage',
   'f471' :   'emotion_affair',
   'f472' :   'emotion_gay',
   'f473' :   'comic_cosplay',
   'f474' :   'comic_info',
   'f475' :   'comic_dongmanpandian', 
   'f476' :   'comic_dongmanxuanfa',
   'f477' :   'comic_gaoxiaomanhua',
   'f478' :   'comic_haizeiwang',
   'f479' :   'comic_huoyingrenzhe',
   'f480' :   'comic_kenan',
   'f481' :   'comic_kongbumanhua',
   'f482' :   'comic_lianzaimanhua',
   'f483' :   'comic_longzhu',
   'f484' :   'comic_nannvshengm...', 
   'f485' :   'comic_neihanmanhua',
   'f486' :   'comic_othermanhua',
   'f487' :   'comic_seximanhua',
   'f488' :   'comic_shengyou',
   'f489' :   'comic_wuyemanhua',
   'f490' :   'comic_xieemanhua',
   'f491' :   'comic_xuanyimanhua',
   'f492' :   'comic_manwei',
   'f493' :   'comic_guoman',
   'f494' :   'comic_altman',
   'f495' :   'comic_jinjidejuren',
   'f496' :   'comic_works',
   'f497' :   'houseliving_decro...', 
   'f498' :   'houseliving_fengshui', 
   'f499' :   'houseliving_handc...', 
   'f500' :   'houseliving_jiadian',
   'f501' :   'houseliving_plant',
   'f502' :   'houseliving_gear',
   'f503' :   'lifestyle_coffee',
   'f504' :   'lifestyle_fishing',
   'f505' :   'lifestyle_jianfei',
   'f506' :   'lifestyle_liqueur',
   'f507' :   'lifestyle_martial',
   'f508' :   'lifestyle_paobu',
   'f509' :   'lifestyle_tea',
   'f510' :   'lifestyle_yoga',
   'f511' :   'lifestyle_aerobics',
   'f512' :   'lifestyle_dance',
   'f513' :   'lifestyle_taiji',
   'f514' :   'lifestyle_wine',
   'f515' :   'lifestyle_fitness',
   'f516' :   'lifestyle_taoyi',
   'f517' :   'lifestyle_psdance',
   'f518' :   'science_space',
   'f519' :   'science_popular',
   'f520' :   'science_fiction',
   'f521' :   'photography_skills',
   'f522' :   'photography_tool',
   'f523' :   'photography_works',
   'f524' :   'career_business',
   'f525' :   'career_common',
   'f526' :   'career_hr',
   'f527' :   'career_market',
   'f528' :   'career_venture',
   'f529' :   'career_shop',
   'f530' :   'wedding_prepare',
   'f531' :   'wedding_photos',
   'f532' :   'qipa-fashion',
   'f533' :   'qipa-tech',
   'f534' :   'qipa-pet',
   'f535' :   'qipa-edu',
   'f536' :   'qipa-baby',
   'f537' :   'qipa-game',
   'f538' :   'qipa-cate'
}
